### ISSUE TITLE
FrmSpiegLinAbbUrspr speichern

### ISSUE THREAD

**Issue by tschar** [Softwareprojekt/Sisyphus#10]
Beim speichern tritt ein Fehler auf:

*************\* Ausnahmetext **************
System.NullReferenceException: Der Objektverweis wurde nicht auf eine Objektinstanz festgelegt.
   bei SoftwareProjekt.Forms.AbstractView.SaveState() in Sisyphus_source_code_cs\SoftwareProjekt\Forms\AbstractView.cs:Zeile 128.
   bei SoftwareProjekt.Classes.Controller.RemoveExercise(IView view) in Sisyphus_source_code_cs\SoftwareProjekt\Classes\Controller.cs:Zeile 158.

Mal abgesehen, dass ich gerade noch einen Fix hochgeladen habe, weil Controlname nicht vorhanden ist, sondern ab jetzt Text. Da war das Repo wohl nicht synchronisiert.

Gruß
Tschar

**Comment by jodli** [comment]
Siehe #11.

**Comment by tschar** [comment]
Ist der gleiche Fehler, wie bei #11 --> der hier kann zu.
