### ISSUE TITLE
richtextbox

### ISSUE THREAD

**Issue by TecateMan** [Softwareprojekt/Sisyphus#11]
Wer zum Teufel zerstört dauernd die verdammte Textbox????

**Comment by Lennok** [comment]
Ich

**Comment by TecateMan** [comment]
Naja, wenigstens gibst du es zu...  
Eigentlich ist es mir ja egal, aber warum?

**Comment by Lennok** [comment]
Der Grund ist weil es  nicht anders funktioniert.
Richtextbox der Notizen darf nicht in der Form sein,  weil sonst in der
loadstate des workbooks zu einer cross thread exception kommt.  Deshalb
muss die txtbox in der acbstact view sein,  welche vom Designer nicht
angezeigt werden kann.
Irgendjemand hat das zurück  geändert.
Hoffe das hilft.  Bitte  morgen wieder Ansprechbar

**Comment by wolfpirker** [comment]
Heißt das die Notizfelder sind alle ziemlich nutzlos unter den Übungen? Weil die eh nicht gespeichert und geladen werden können, oder ist das wieder ein anderer Issue?

**Comment by jodli** [comment]
Die Notizen werden nur gespeichert wenn DEBUG nicht definiert ist.
Also wenn im Release Modus gebaut wird, dann passt alles. :)

**Comment by wolfpirker** [comment]
ah ok, dann ists ja gut.

**Comment by jodli** [comment]
WAS WARUM!
