### ISSUE TITLE
Fraktal rendern mit Chaosspiel

### ISSUE THREAD

**Issue by tschar** [Softwareprojekt/Sisyphus#13]
Beim Speichern tritt folgender Fehler auf:

System.ArgumentException: Ein Element mit dem gleichen Schlüssel wurde bereits hinzugefügt.
   bei System.ThrowHelper.ThrowArgumentException(ExceptionResource resource)
   bei System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
   bei System.Collections.Generic.Dictionary`2.Add(TKey key, TValue value)
   bei SoftwareProjekt.Forms.AbstractView.SaveState() in Sisyphus-dev_source_code_cs\SoftwareProjekt\Forms\AbstractView.cs:Zeile 128.

Ein anderer Bug als der vorhin gemeldete.

**Comment by jodli** [comment]
Fixed in a0e68131a1769e01b39cfe3f237085794c9074b1.
