### ISSUE TITLE
VisualBasic PowerPacks

### ISSUE THREAD

**Issue by jodli** [Softwareprojekt/Sisyphus#14]
Nicht mehr kompilierbar seit 8497ad43556c9dbc302c7dc6cee6930e098c5c22.
The type or namespace name 'PowerPacks' does not exist in the namespace 'Microsoft.VisualBasic' (are you missing an assembly reference?)

**Comment by tschar** [comment]
Programm lässt sich kompilieren?

Evtl ein Merge – Conflict bei dir was die .csproj datei angeht?

Ein komplett heruntergeladenes Archiv lässt sich bauen!

Und schock mich nicht so :D

Von: jodli [mailto:notifications@github.com] 
Gesendet: Sonntag, 6. Juli 2014 11:57
An: Softwareprojekt/Sisyphus
Cc: tschar
Betreff: [Sisyphus] VisualBasic PowerPacks (#14)

Nicht mehr kompilierbar seit  https://github.com/Softwareprojekt/Sisyphus/commit/8497ad43556c9dbc302c7dc6cee6930e098c5c22 8497ad4.
The type or namespace name 'PowerPacks' does not exist in the namespace 'Microsoft.VisualBasic' (are you missing an assembly reference?)

**Comment by jodli** [comment]
Also ich weiss ja nicht was fuer Pakete du da extra installiert hast, aber bei mir geht das auch neu geklont nicht...

**Comment by jodli** [comment]
Fixed in 87a2a317c476b3e4eba10929d5da7e740c5f7560.

**Comment by tschar** [comment]
VS 2012 war die ausgemachte Tool - Version, da ist die dll vorhanden.
