### ISSUE TITLE
Mindmap / ZuordvorLinAbb

### ISSUE THREAD

**Issue by jodli** [Softwareprojekt/Sisyphus#16]
Der Name auf der MindMap ist: "Vertraeglichkeit mit Linearkombination"
Der Name der Uebung / Form ist: "Zuordnungsvorschrift einer linearen Abbildung"

Ist das so gewollt?

**Comment by manustr** [comment]
Ich hab das so vorgeschlagen, weils auch so auf dem pdf zur Mindmap steht, dass wir von ihm bekommen haben. Wir könnens aber auch anders nennen.

**Comment by jodli** [comment]
Fixed in b0e8996c78ad2698184660d37caa376358938812.
