### ISSUE TITLE
Existierendes Arbeitsbuch ersetzen, Exception in der Workbookklasse

### ISSUE THREAD

**Issue by wolfpirker** [Softwareprojekt/Sisyphus#18]
ich hab das Verhalten wenn man nach "Arbeitsbuch anlegen" einen Namen angibt den es schon gibt, so geändert, dass man dann das Arbeitsbuch entweder Ersetzen kann oder abbricht, weil das so im entsprechenden Use-Case ist. 

Jedoch tritt unter Workbook.Instance.DeleteWorkbook ein Fehler auf. Eine IOException, weil die Bilder in der Anwendung noch geladen sind, und daher der Ordner mit den Screenshots nicht gelöscht werden kann.

Eine Lösungsmöglichkeit wäre, dass man der Methode DeleteWorkbook den Namen des Arbeitsbuchs übergibt, und das Arbeitsbuch vorher schließt (d.h. Workbook.Instance.Username ändert).

**Comment by Lennok** [comment]
fixed in 4f218e49f8b275fe15ed0eb9782c7a4d21d14a22.
Please check function call in FrmMain Line 1007

**Comment by wolfpirker** [comment]
Danke, funktioniert jetzt :)
