### ISSUE TITLE
FrmLinAbbSumBelVek

### ISSUE THREAD

**Issue by jodli** [Softwareprojekt/Sisyphus#19]
Form Resize:
- [ ] MinimumSize der Form setzen, bei der sich nichts ueberschneidet.
- [ ] Dateneingabe Groupbox hat keinen Anchor und veraendert die Position nicht bei Skalierung der Form.
- [ ] Der Pfeil skaliert nicht mit der Groesse der Form.

Gleichung:
- [ ] Sollte die Gleichung den Pfeil ausfuellen? Ich finde auch die Schrift sehr klein.
- [ ] Vektoren x und y werden eingegeben, aber in der Gleichung nicht ausformuliert.
- [ ] Matrix M bei erstem Gleichungsschritt nicht ausformulieren.
  -> "f(x) = M \* (x + y)"

Beschriftung:
- [ ] Vektoren (x, y) und Matrix bei Dateneingabe haben keine richtige Beschriftung.

**Comment by jodli** [comment]
P.S.:
- [ ] : "- [ ]"
- [x] : "- [x]"

**Comment by tschar** [comment]
Schriftgröße wäre änderbar. 
@TecateMan am CtlFormularDraw gibt es eine Eigenschaft FontSize, die einfach setzen.

**Comment by TecateMan** [comment]
Bin dran!

**Comment by jodli** [comment]
Form Resize:
- [ ] MinimumSize der Form setzen, bei der sich nichts ueberschneidet.
- [ ] Dateneingabe Groupbox hat keinen Anchor und veraendert die Position nicht bei Skalierung der Form.
- [ ] Der Pfeil skaliert nicht mit der Groesse der Form.

Gleichung:
- [x] Sollte die Gleichung den Pfeil ausfuellen? Ich finde auch die Schrift sehr klein.
- [x] Vektoren x und y werden eingegeben, aber in der Gleichung nicht ausformuliert.
- [x] Matrix M bei erstem Gleichungsschritt nicht ausformulieren. -> "f(x) = M \* (x + y)"

Siehe 799cdeb41123e6d6c67aa2af2da690507005bea7.

Beschriftung:
- [x] Vektoren (x, y) und Matrix bei Dateneingabe haben keine richtige Beschriftung.

Siehe 3ec71347ccd4e7cbf927e0b3f54467d56494b8f5
