### ISSUE TITLE
Zuordnungsvorschrift einer affinen Abbildung lässt sich nicht speichern

### ISSUE THREAD

**Issue by tschar** [Softwareprojekt/Sisyphus#20]
Zuordnungsvorschrift einer linearen Abbildung lässt sich nicht speichern. Es tritt keine Exception oder ähnliches auf, am Ende der Übung wird korrekt abgefragt, ob man speichern will, drückt man ja, passiert nichts. 

Es wird anscheinend kein Bild gespeichert, ist zu mindestens keines für die Übung in dem entsprechenden Workbook - Ordner.

Das Workbook enthält zur ZuordnungsvorschriftEinerAffAbb:

```
<WorkbookEntry>
  <CreationDate>07/07/2014 08:51:02</CreationDate>
  <ExerciseID>ZuordungsvorschriftEinerAffAbb</ExerciseID>
  <NumberOfDictionaryEntries>0</NumberOfDictionaryEntries>
</WorkbookEntry>
```

Bis nachher.

Gruß
Julian

**Comment by jodli** [comment]
Fixed in 5d17efe60dd1c1141106197a16b3a7043891f7d5.
