### ISSUE TITLE
Beschriftung Matrix & Vektor Input

### ISSUE THREAD

**Issue by TecateMan** [Softwareprojekt/Sisyphus#21]
Langsam aber sicher hab ich echt die Schnauze voll! Am Freitag habe ich alle Controls sauber benannt und jetzt steht wieder überall Mist drin! Ich kann ja nie fertig werden, wenn dauernd jemand alles rückgängig macht.

Außerdem funktioniert das Property für die Namensänderung nicht. Wer auch immer wieder da seine Arschkratzer dran hatte, bringt das wieder in Ordnung.

**Comment by jodli** [comment]
Das warst du selber ;)
Siehe b0d5bdc3ca3bb044c3505e7199f7504ebac287e8 und a6e92d6fa0624f5073b7318659eca8208ed59c7f.

Das Text Property sollte jetzt auch im Designer funktionieren. Fixed in 1eb3f3654ac1a948f9a42e62e4a42e194b7f9a3e.

**Comment by TecateMan** [comment]
Mit Sicherheit nicht! Das Property, das ich angelegt hatte hieß ControlName (damit es auch der letzte Idiot kapiert, hat aber auch nicht funktioniert)
