### ISSUE TITLE
Main-GUI

### ISSUE THREAD

**Issue by MKaesewieter** [Softwareprojekt/Sisyphus#22]
Also hab jetzt die Main GUI durchgetestet.
Paar Sachen sind mir noch aufgefalln die noch nicht ganz funktionieren:
1. Der Administartor kann keine neue Übung hinzufügen/erstellen
2. Manche Übungen kann man beim schließen nicht speichern bzw. es wird nichts ins arbeitsbuch übertragen was man anschließend wieder laden kann.

**Comment by tschar** [comment]
Wie melde ich einen Bug?
1. Suche in den vorhanden Issues, ob Bug schon gemeldet. (issue #20 meldet den Fehler "Zuordnungsvorschrift einer affinen Abbildung lässt sich nicht speichern" )
2. Fehlerbeschreibung (Übung nicht speicherbar)
3. Konkretisieren (Was / Welche klasse funktioniert, wann nicht?)
4. evtl. Exception - Beschreibungen oder nachweisbare Einträge anhängen, bspw. Eintrag aus dem Xml - Workbook.

und viel wichtiger, überprüfen, ob es überhaupt noch Bestandteil der Testspezifikation ist. (bspw. Adminstrator neue Übung hinzufügen ist derzeit nicht mehr Bestandteil)
