### ISSUE TITLE
Was muss in die Formel auf FrmDrehLinAbbUrsp?

### ISSUE THREAD

**Issue by TecateMan** [Softwareprojekt/Sisyphus#23]
Weiß das jemand?

**Comment by HeisenbugX** [comment]
In dem Pdf "Drehung, Spiegelung, Streckung " ist dafür ein Beispiel. Da muss nur noch phi und der x Vektor ersetzt werden.

**Comment by wolfpirker** [comment]
es gibt einen Unterschied zwischen unserer Übung und dem PDF. Eigentlich sollte man die Einheitsvektoren (Vektor 2, und Vektor 3) nicht ändern können. 

Also ich würd sagen du nimmst nur Vektor 1 und den Winkel. Den Winkel setzt du in die lineare Matrix ein. Statt pi/2 kannst du wohl auch 90° schreiben, wenn das dann einfacher ist. In der ersten Spalte der Matrix ist der Winkel von Einheitsvektor 1 und die 2. gehört zum Einheitsvektor 2. 

Die Formel stimmt dann aber nur mit dem angezeigten Bildern überein, wenn man für Vektor 2 [1, 0] wählt und für Vektor 3 [0, 1]. Also das wäre eigentlich zu ändern, dass man die Einheitsvektoren nicht ändern kann (siehe auch #25).

**Comment by manustr** [comment]
Genau, Einheitsvektoren sind Einheitsvektoren und dürfen nicht verändert werden können.
