### ISSUE TITLE
Spiegelung an einer Ursprungsgeraden SpiegelungLinAbbanUrsprungsgeraden 

### ISSUE THREAD

**Issue by HeisenbugX** [Softwareprojekt/Sisyphus#27]
Beim Testen ist mir aufgefallen im Ausgabediagramm wird der Winkel mit einer Gerade eingezeichnet, beim erneuten berechnen bleibt diese Gerade bestehen und es wird eine neue Winkelgerade dazu gezeichnet.

**Comment by manustr** [comment]
fixed
