### ISSUE TITLE
Coding Guideline

### ISSUE THREAD

**Issue by jodli** [Softwareprojekt/Sisyphus#3]
Hi!
Wollen wir in den Guidelines eine Sache anpassen?

Ungarische Notation ist nervig und kostet meiner Meinung nach nur Zeit.
Visual Studio ist in der Hinsicht schon ganz praktisch, weil der Typ leicht angezeigt werden kann.
Siehe auch: http://msdn.microsoft.com/en-us/library/ms229045

**Comment by tschar** [comment]
Der Nachteil an ungarischer Notation ist definitiv, dass man sich einlesen muss. Wenn man es kann, bist halt schneller, als ohne. 

Wir können das von mir aus gerne weglassen.

Allerdings hätte ich gerne weiterhin einen Separator für Member - Variablen, wie z.B. das "_" vornedran. (bspw. _XmlTree) Ist schlicht übersichtlicher als ohne.
