### ISSUE TITLE
Floats werden nicht mehr richtig geparst

### ISSUE THREAD

**Issue by wolfpirker** [Softwareprojekt/Sisyphus#31]
wenn man die Übung z.B. "Drehung lineare Abbildung um Ursprung" mit Eingabewerten speichert, danach wieder öffnet, stehen in den Feldern n. Def. obwohl hierzu Werte gespeichert wurden.

Ich hab grob geprüft welcher commit den Bug wohl gebracht hat: 
um 00:07 (vor 20 Stunden) hat es bei den Eingabevektoren die gespeicherten Werte nicht mehr geladen (commit https://github.com/Softwareprojekt/Sisyphus/commit/9f186925a38ac4c42e6a9582541ebc4820b6eed8). Um 00:07 hat das Laden der gespeicherten Werte zumindest noch bei den Eingabevektoren funktioniert - aber nicht bei den berechneten Werten. Dazwischen sind zwei Commits von Lennok.

Die Ergebnisse werden bei dieser Übung auch nicht mehr gespeichert.

**Comment by wolfpirker** [comment]
von diesem Bug sind inzwischen die meisten oder gar alle Übungen betroffen.

**Comment by Lennok** [comment]
hast du es im release modus probiert? da gehts bei mir

**Comment by Lennok** [comment]
es speichert im Debug-Modus die Notizen nicht, damit kann er sie auch nicht laden und bricht den Ladevorgang ab. Im Release-Modus ist die Richtextbox für die Notizen in der AbstractView drin, daher wird das Arbeitsbuch nur im Release-Modus funktionieren

**Comment by wolfpirker** [comment]
ah ja zumindest die Eingabevektoren werden dann geladen, wenn als Release kompiliert. 

In mehreren Übungen werden aber anscheinend die Matrizen noch nicht richtig geladen, z.B. "Verträglichkeit mit Vielfachen bei Vektoren". Und die Ergebnisbilder und Vektoren werden auch nicht richtig geladen.

**Comment by Lennok** [comment]
kann ich dir sagen.
bei LinAbbVielBelVek.cs ab Zeile 188 in der Funktion LoadState wird die matrix nicht geladen ;-)

**Comment by Lennok** [comment]
und die Notes auch nicht

**Comment by wolfpirker** [comment]
ah ok, dann fix ich das, oder bist du da dran?

**Comment by Lennok** [comment]
in der form kann ich das machen

**Comment by wolfpirker** [comment]
ok dann schau ich ob woanders das noch gemacht werden muss.

**Comment by wolfpirker** [comment]
gefixt (ausgenommen Ergebnisplots, wo's nicht wichtig ist).
