### ISSUE TITLE
Fraktal rendern mit Chaosspiel 

### ISSUE THREAD

**Issue by HeisenbugX** [Softwareprojekt/Sisyphus#32]
Bei Eingabe von hohen Werten in "Anzahl Iterationen" wird eine Exception ausgelöst, die Exception tritt noch früher auf wenn der Wert in "Anzahl Redervorgängen" entsprechend hoch ist.

Beispiel: Anzahl Iterationen 500000000, Anzahl Redervorgängen 10, sonnst default Werte von Farm

**Comment by wolfpirker** [comment]
ich würde vorschlagen, wir kennzeichnen alle Issues die nicht relevant für die Systemabnahme sind mit WONTFIX. Bei der Menge an Issues verliert man sonst noch leicht den Überblick über die wichtigeren Sachen.

**Comment by Lennok** [comment]
bei 500 milliionen Iterationen darf ein OutOfMemoryException kommen.
Dh mein erstes Array ist voll mit 25millionen Pixeln ... noch fragen?!

**Comment by HeisenbugX** [comment]
Das war nie ein Frage sondern ein Bug^^
