### ISSUE TITLE
Testprotokoll hochgeladen

### ISSUE THREAD

**Issue by HeinzHartz** [Softwareprojekt/Sisyphus#33]
Hab die Berichte, die ich von Tilo bekommen hab, verarbeitet und hochgeladen, bei Verbesserungsvorschlägen oder aktualisierten Daten bitte Bescheid geben. Danke

**Comment by wolfpirker** [comment]
Im Testprotokoll die NullException in ID22 ist gefixt. Wenn man keine Übung ausgewählt hat, wird auch ein Hinweis angezeigt, dass man vor dem Löschen eine Übung auswählen soll.

Wurde die Testspezifikation schon abgegeben? Mir sind da zu zwei Use-Cases (ID1 und 2) noch Sachen aufgefallen. Zum Beispiel wird das Arbeitsheft erst nach speichern einer Übung angelegt. Bei ID2 fehlt der Hinweis, was passiert wenn es mehrere Arbeitshefte gibt.

**Comment by jodli** [comment]
Use-Case "Drehung_lin_Abb_um_Ursprung_studieren" ist nicht mehr aktuell. 
Alle aufgefuehrten Fehler, ausser die angezeigten Formeln, wurden gefixed.

Use-Case „SpiegelungLinAbbanUrsprungsgeraden“
Alle aufgefuehrten Fehler, ausser die angezeigten Formeln,  wurden gefixed.

Use-Case „Umkehrung_lin_Abb_studieren“
Alle aufgefuehrten Fehler wurden gefixed.
