### ISSUE TITLE
Systementwurf v1.3

### ISSUE THREAD

**Issue by jodli** [Softwareprojekt/Sisyphus#34]
- Der blaue Text gehoert immer noch rausgeloescht.
- Es gibt immer noch verschiedene Schriftarten und -groessen.
- Klassendiagramme sind nicht aktuell.
- Ablaufdiagramm aus v1.2 unter _5 Designabsicherung_ fehlt in v1.3.

**Comment by wolfpirker** [comment]
die Bibliothek MimeTeX.dll die in dem Systementwurf aufgeführt ist verwendet Sisyphus nicht mehr. Zwei Libraries PDFClown und MathML sind hinzugekommen.
