### ISSUE TITLE
FloatInput-Textbox

### ISSUE THREAD

**Issue by Lennok** [Softwareprojekt/Sisyphus#5]
Bitte alle Textboxen in FloatInput-Texboxen ändern.
Am einfachsten im Designer den Konstruktor ändern und am Ende der Datei die Definition.
Das Matrix- und das Vectorcontrol wurde schon geändert.

**Comment by jodli** [comment]
Bei [FrmDrehLinAbbUrsp](_source/_code/_cs/SoftwareProjekt/Forms/FrmDrehLinAbbUrsp.cs) ist auch alles geaendert.
GUI sieht uebrigens grauselig aus... :o
