### ISSUE TITLE
Koordinatensystem

### ISSUE THREAD

**Issue by jodli** [Softwareprojekt/Sisyphus#6]
Ein paar Sachen die mir beim Koordinatensystem aufgefallen sind (Commit: 46cabf66f2e8b4f7d8598380022e16595a469b30)
Bei Y Achse EndValue = 12 und Scale = .5 stuertzt das Programm ab, wenn man das Fenster zu klein zieht. Ich schaetze das liegt an den Skalierungsstrichen die sich ueberlagern?
Y Achsen Skalierung stimmt nicht. Punkt bei y = 1 ist nicht auf 1 sondern drunter... Benutzt du integers zum Zeichnen? Probleme mit dem Runden?
LineSegment mit Startpunkt = Endpunkt stuertzt auch ab.
Refresh() zeichnet das KoordinatenSystem nach der Berechnung nicht neu? Keine Ahnung woran das liegt...

**Comment by tschar** [comment]
Zu viele Segmente führen durchaus zum Absturz ja, deshalb hatte ich mir auch schon überlegt, dass ich manche Skalierungen vom Programm selbst als falsch definiere.

Lustigerweise tritt das Problem mit der Ungenauigkeit auf meinem großen Monitor nicht auf, auf meinem Laptop schon, werde ich mir auf jeden Fall noch einmal anschauen. Auf PointF kommt es da übrigens nicht an, da ist der Fehlerbereich viel zu groß, eher auf die dahinter verwendeten integers.

Der Fehler tritt interessanterweise ab der Koordinate 3 (also bei Skalierung 0 - 5 bei 0.5) nicht mehr auf.

Ein LineSegment mit Startpunkt = Endpunkt ist ein Punkt und keine Linie, von daher eine falsche Eingabe.

Das mit dem Refresh() ist mir auch schon aufgefallen, hatte aber keine Erklärung für. Ich empfehle Invalidate() zu verwenden, das hat bei mir funktioniert.

**Comment by Lennok** [comment]
tschar: Ein LineSegment mit Startpunkt = Endpunkt ist ein Punkt und keine Linie, von daher eine falsche Eingabe.
ich: schonmal was von einem Nullvektor gehört?

tschar: Das mit dem Refresh() ist mir auch schon aufgefallen, hatte aber keine Erklärung für. Ich empfehle Invalidate() zu verwenden, das hat bei mir funktioniert.
ich (bzw msdn): Forces the control to _invalidate_ its client area and immediately redraw itself and any child controls.
also ist im refresh ein invalidate und update drin ;-)

**Comment by jodli** [comment]
Dass da Integers dahinter liegen weiss ich schon und hab ich ja auch schon erwaehnt...
Kann man das vielleicht noch umschreiben, damit sich das auch ordentlich mit dem Fenster skalieren laesst? Auch wenn der Punkt an der richtigen Stelle ist, bringt das ja nix wenn die Punkte da immer nur auf ganze Int Zahlen schnappen...

**Comment by tschar** [comment]
Lennok: schonmal was von einem Nullvektor gehört? 
Tschar: Ja habe ich, ändert nichts daran, dass ein Vektor mit Endpunkt = Startpunkt ein Punkt ist. (logisch gesehen) Ich kann aber gerne die Spezialbehandlung für den Nullvektor einfügen. 

Lennok: Forces the control to invalidate its client area and immediately redraw itself and any child controls.
also ist im refresh ein invalidate und update drin ;-)

Tschar: Faszinierend, aber wieso funktioniert das dann bei mir mit Invalidate und nicht mit Refresh?

Jodli: Auch wenn der Punkt an der richtigen Stelle ist, bringt das ja nix wenn die Punkte da immer nur auf ganze Int Zahlen schnappen...
Tschar: Ich verstehe nicht ganz was du meinst. 

Jodli: Kann man das vielleicht noch umschreiben, damit sich das auch ordentlich mit dem Fenster skalieren laesst?

Tschar: das war der ursprünliche Plan und ich wollte das noch bearbeiten, bloß hatte ich gestern Abend keine Lust noch was zu machen.

**Comment by tschar** [comment]
ist das hier noch relevant?
