### ISSUE TITLE
abstractView nicht mehr abstract

### ISSUE THREAD

**Issue by wolfpirker** [Softwareprojekt/Sisyphus#7]
Ich hab die Klasse AbstractView auf eine nicht-abstrakte Klasse umgeändert und bin mir nicht sicher, ob das sinnvoll ist.

Grund war der Fehler, dass man einige Forms im Visual Studio Designer nicht anzeigen konnte, mit der Begründung dass diese Klasse als abstrakt deklariert ist. 

Jetzt stell ich fest, dass wenn man AbstractView wieder abstract macht und die jetzt virtuell deklarierten Methoden der Klasse, alle abstract macht, es nicht mehr zu dem früheren Fehler kommt. Ich kann mir nicht erklären warum. Vielleicht weiß das jemand?

Der Issue ist dazu da, um zu klären ob AbstractView wieder abstrakt sein soll. Wenn nicht, sollte man evtl. auch den Namen der Klasse ändern.

**Comment by jodli** [comment]
Also das war eigentlich nur dazu gedacht allgemeine Methoden nur einfach zu implementieren. 
Haben wir ueberhaupt noch solche Methoden oder sind die alle nur in den jeweiligen Views?
Ansonsten wird ja eh nur ueber das Interface kommuniziert... 

Warum das jetzt geht weiss ich allerdings auch nicht :D

**Comment by wolfpirker** [comment]
ok der issue ist nicht so wichtig. Scheint ja so wies jetzt ist zu funktionieren.
