### ISSUE TITLE
FrmSpiegLinAbbUrsp

### ISSUE THREAD

**Issue by manustr** [Softwareprojekt/Sisyphus#9]
In der Form SpiegLinAbbUrsp bei dem Winkel bitte ein FloatInput Steuerelement statt der TextBox.

**Comment by TecateMan** [comment]
In Arbeit!

**Comment by HeinzHartz** [comment]
Wer hat die softwareprojekt.csproj zerstört? Nach dem letzten Sync vor 3 stunden geht’s nicht mehr ^^

Von: TecateMan [mailto:notifications@github.com] 
Gesendet: Samstag, 5. Juli 2014 11:48
An: Softwareprojekt/Sisyphus
Betreff: Re: [Sisyphus] FrmSpiegLinAbbUrsp (#9)

Closed #9 https://github.com/Softwareprojekt/Sisyphus/issues/9 .

**Comment by tschar** [comment]
is fixed.
